---
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  profiles: cloud
  cloud:
    services:
      registrationMethod: route
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  client:
    registerWithEureka: true
    serviceUrl: ${vcap.services.discovery.credentials.uri}/eureka/
---
spring:
  profiles: mysql
  datasource:
    url: ${cloud.services.mysql.connection.jdbcurl}
    username: ${cloud.services.mysql.connection.username}
    password: ${cloud.services.mysql.connection.password}
    tomcat:
      test-on-borrow: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
